---
- name: Debian | install packages
  apt:
   name={{item}}
   state=latest
   update_cache=yes
  with_items:
   - git
   - python-setuptools
   - python-dev
   - build-essential

- name: Debian | easy_install - Install pip
  easy_install:
   name=pip

- name: Debian | pip - Install Packages
  pip:
   name={{item}}
   state=latest
  with_items:
   - paramiko
   - PyYAML
   - Jinja2
   - httplib2
   - simplejson
   - six
   - redis

- name: Debian | Clone Ansible from github.com
  git:
   repo=https://github.com/ansible/ansible.git
   recursive=yes
   dest={{ansible_inst.dir}}
   accept_hostkey=yes
   update=no

- name: Debian | Add Ansible env-setup hack system wide
  template:
   src=ansible-env-setup.j2
   dest=/etc/profile.d/ansible-env-setup.sh
   owner=root
   group=root
   mode=0755
  when: ansible_inst.add_evn_setup_hack_sys_wide
